language: node_js
node_js:
  - '10'
branches:
  only:
    - master
install:
  - npm run setup
script:
  - npm run test
deploy:
  # deploy on release, to markbind.org
  - provider: script
    script: >-
      cd docs &&
      ../packages/cli/index.js build -s ug-site.json &&
      ../packages/cli/index.js deploy -s ug-site.json --travis
    skip_cleanup: true
    on:
      repo: MarkBind/markbind
      tags: true
      condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+
  # deploy on any commit to master, to markbind.org/devdocs
  - provider: script
    script: >-
      npm run build:web &&
      cd docs &&
      ../packages/cli/index.js build -s dg-site.json &&
      ../packages/cli/index.js deploy -s dg-site.json --travis
    skip_cleanup: true
    on:
      repo: MarkBind/markbind
cache:
  directories:
    - node_modules
sudo: false
