name: New Contributor Action
on: 
    pull_request_target:
        types: [closed]

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
  check-new-contributor:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Check new contributor
        uses: actions/github-script@v7
        with:
          script: |
            const prAuthor = context.payload.pull_request.user.login;
            const contributors = await github.paginate(
              github.rest.repos.listContributors, {
                owner: context.repo.owner,
                repo: context.repo.repo
              }
            );

            const isAlreadyContributor = contributors.some(contributor => contributor.login === prAuthor);
            
            if (!isAlreadyContributor) {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `**Welcome**, @${prAuthor}! ðŸŽ‰ Thank you for your contribution to the MarkBind project!

                  Do remember to request someone to add you as a official contributor to our repository, if you want to of course! See the full list of contributors [here](https://markbind.org/about.html) âœ¨`
              });
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            