name: New Contributor Action
on: 
    pull_request_target:
        types: [closed]

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
  check-new-contributor:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write
    steps:
      - name: Check new contributor
        uses: actions/github-script@v7
        with:
          script: |
            const prAuthor = context.payload.pull_request.user.login;
            const repoOwner = context.repo.owner;
            const repoName = context.repo.repo;
            const currentPR = context.payload.pull_request.number;
            const mergedPRs = await github.paginate(
              github.rest.pulls.list,
              {
                owner: repoOwner,
                repo: repoName,
                state: 'closed',
                per_page: 100
              },
              (response) => response.data.filter(pr => pr.merged_at != null && pr.user.login === prAuthor && pr.number !== currentPR)
            );
            console.log(mergedPRs)
            if (mergedPRs.length == 0) {
              github.rest.issues.createComment({
                issue_number: context.payload.pull_request.number,
                owner: repoOwner,
                repo: repoName,
                body: `**Welcome**, @${prAuthor}! ðŸŽ‰ Thank you for your contribution to the MarkBind project!\n\nDo remember to request someone to add you as a official contributor to our repository, if you want to of course!\n\nSee the full list of contributors [here](https://markbind.org/about.html). âœ¨`
              });
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            